global using System;
global using System.Runtime.InteropServices;
global using System.Runtime.CompilerServices;
global using NekkoOS.Int;
global using NekkoOS.Kernel;
global using NekkoOS.Kernel.Crypto;
global using NekkoOS.Kernel.Driver;
global using NekkoOS.Kernel.Lib;
global using NekkoOS.Kernel.Utilities;